import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import test from 'node:test';

test('unit management matches the operational hierarchy and keeps complete unit and admin fields reachable', async () => {
  const [page, createPage, detailPage, shell, styles] = await Promise.all([
    readFile('src/app/(main)/unit-management/unit-management-client.tsx', 'utf8'),
    readFile('src/app/(main)/unit-management/new/unit-create-client.tsx', 'utf8'),
    readFile('src/app/(main)/unit-management/[unitId]/page.tsx', 'utf8'),
    readFile('src/components/main-shell.tsx', 'utf8'),
    readFile('src/app/globals.css', 'utf8'),
  ]);

  await access('public/unit-management-hero.png');
  assert.match(styles, /unit-management-hero\.png/);
  assert.doesNotMatch(styles, /\.unit-hero::before/);
  assert.match(styles, /background-size:\s*cover,\s*cover/);
  assert.match(styles, /background-position:\s*center,\s*right 85%/);
  assert.match(page, /<Link href="\/unit-management\/new">/);
  assert.match(page, /router\.push\(`\/unit-management\/\$\{unit\.id\}`\)/);
  assert.match(page, /updateUnitAdminAction/);
  assert.match(page, /Detail akun admin unit/);
  assert.match(page, /<BadgeCheck className="h-10 w-10"/);
  assert.match(page, /Kode unit/);
  assert.match(page, /unit\.unitCode \|\| formatUnitCodePreview\(unit\.domicile, unit\.prefix\)/);
  assert.equal((page.match(/font-sans tabular-nums/g) ?? []).length, 4);
  assert.doesNotMatch(page, /font-mono/);
  assert.match(page, /setIsAdminDialogOpen\(true\)/);
  assert.doesNotMatch(page, /href="\/unit-management\/new\?mode=admin"/);
  assert.match(page, /<Dialog open=\{isAdminDialogOpen\}/);
  assert.match(page, /unit-admin-dialog-header !grid !text-left/);
  assert.match(page, /unit-admin-fields/);
  assert.match(page, /unit-admin-field--unit/);
  assert.match(page, /adminError && <p/);
  assert.match(page, /Tambah akun admin unit/);
  assert.match(page, /Unit terkait/);
  assert.match(page, /Nama admin unit/);
  assert.match(page, /Email akun/);
  assert.match(page, /Nomor telepon/);
  assert.match(page, /Password awal/);
  assert.doesNotMatch(page, /id="admin-domicile"/);
  assert.doesNotMatch(page, /id="admin-address"/);
  assert.match(createPage, /Tambah akun admin unit/);
  assert.match(createPage, /Pilih unit terkait/);
  assert.match(createPage, /<Select name="unitId"/);
  assert.match(createPage, /name="prefix"/);
  assert.match(createPage, /pattern="\[0-9\]\{5\}"/);
  assert.match(createPage, /formatUnitCodePreview\(province, prefix\)/);
  assert.doesNotMatch(createPage, /id="unit-domicile"/);
  assert.match(createPage, /name="domicile" value=\{province\}/);
  assert.match(createPage, /Terbentuk otomatis dari domisili dan kode unit 5 digit\./);
  assert.match(createPage, /router\.push\('\/unit-management'\)/);
  assert.match(createPage, /updateUnitAction/);
  assert.match(createPage, /mode: 'unit' \| 'admin' \| 'edit'/);
  assert.match(createPage, /Detail Unit/);
  assert.doesNotMatch(createPage, /Pencil/);
  assert.match(createPage, /Simpan perubahan/);
  assert.match(createPage, /relatedAdmins/);
  assert.match(createPage, /Sudah tersimpan/);
  assert.match(createPage, /required=\{false\}/);
  assert.match(detailPage, /listUnitAdmins/);
  assert.match(detailPage, /filter\(\(admin\) => admin\.unitId === unit\.id\)/);
  assert.match(createPage, /unit-reference-unit-card/);
  assert.match(createPage, /Pengelola Unit/);
  assert.match(createPage, /Penaksir Unit/);
  assert.match(createPage, /Akun Admin Unit/);
  assert.match(createPage, /Tambahkan akun admin unit/);
  assert.match(createPage, /Link Google Maps Alamat/);
  assert.match(createPage, /name="managers"/);
  assert.match(createPage, /name="appraisers"/);
  assert.match(createPage, /name="admins"/);
  assert.match(createPage, /Domisili <span>\*<\/span>/);
  assert.match(page, /unit-admin-select-content/);
  assert.match(page, /unit-admin-info/);
  assert.match(page, /Simpan/);
  assert.match(styles, /\.unit-admin-dialog\s*\{/);
  assert.doesNotMatch(styles, /Full-size admin account modal/);
  assert.match(page, /!max-w-\[47rem\]/);
  assert.match(styles, /width: min\(calc\(100% - 2rem\), 47rem\)/);
  assert.match(styles, /height: 2\.9rem/);
  assert.match(styles, /\.unit-admin-fields\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(styles, /\.unit-admin-field--unit\s*\{[\s\S]*?grid-column:\s*1\s*\/\s*-1/);
  assert.match(styles, /\.unit-admin-select-trigger\[data-state="open"\]/);
  assert.match(styles, /\.unit-admin-select-content\s*\{/);
  assert.match(styles, /\.unit-admin-select-item\[data-highlighted\]/);
  assert.match(styles, /\.unit-reference-page\s*\{[\s\S]*?83\.5rem/);
  assert.match(styles, /\.unit-reference-select\s*\{[\s\S]*?font-family:\s*'Plus Jakarta Sans', sans-serif/);
  assert.match(styles, /\.unit-reference-select\s*\{[\s\S]*?font-size:\s*\.78rem[\s\S]*?font-weight:\s*650/);
  assert.match(styles, /\.unit-reference-select\s*\{[\s\S]*?font-size:\s*\.92rem/);
  assert.match(styles, /\.unit-admin-select-content\s*\{[\s\S]*?font-family:\s*'Plus Jakarta Sans', sans-serif/);
  assert.match(styles, /\.unit-admin-select-item\s*\{[\s\S]*?font-family:\s*'Plus Jakarta Sans', sans-serif[\s\S]*?font-size:\s*1rem/);
  assert.doesNotMatch(styles, /\.unit-admin-select-item span:last-child/);
  assert.match(page, /unit\.name\} - \$\{unit\.unitCode/);
  assert.match(page, /formatUnitCodePreview\(unit\.domicile, unit\.prefix\)/);
  assert.doesNotMatch(page, /unit-admin-select-code/);
  assert.doesNotMatch(styles, /unit-admin-select-code/);
  assert.match(styles, /\.unit-reference-two-columns\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(page, /Domisili/);
  assert.match(page, /Nomor telepon/);
  assert.match(page, /Nama admin/);
  assert.match(page, /unit-hero-copy/);
  assert.match(page, /unit-hero-stats/);
  assert.match(page, /unit-hero-actions/);
  assert.ok(page.indexOf('unit-hero-stats') < page.indexOf('unit-hero-actions'));
  assert.match(page, /Unit terdaftar/);
  assert.match(page, /Akun admin/);
  assert.match(page, /unit-hero-stat-icon/);
  assert.match(page, /unit-hero-stat-copy/);
  assert.doesNotMatch(page, /unit-hero-stat-divider/);
  assert.match(page, /unit-management-content/);
  assert.doesNotMatch(page, /unit aktif/);
  assert.match(styles, /\.unit-management-content > aside\s*\{\s*display:\s*none/);
  assert.match(styles, /\.unit-hero-stat\s*\{/);
  assert.match(styles, /\.unit-hero-stat-icon\s*\{[\s\S]*?background:\s*#008d84/);
  assert.match(styles, /\.unit-hero-secondary\s*\{[\s\S]*?background:\s*rgba\(255, 255, 255, \.92\) !important/);
  assert.match(styles, /\.unit-hero-primary\s*\{[\s\S]*?background:\s*rgba\(0, 112, 105, \.88\) !important/);
  assert.match(styles, /\.unit-hero-primary:hover\s*\{[\s\S]*?background:\s*rgba\(0, 126, 118, \.43\) !important/);
  assert.match(styles, /\.unit-hero-secondary:hover\s*\{[\s\S]*?background:\s*rgba\(226, 252, 248, \.18\) !important/);
  assert.match(styles, /--background:\s*0 0% 100%/);
  assert.match(styles, /--sidebar-background:\s*192 56% 98%/);
  assert.match(styles, /--naviga-glass-alpha/);
  assert.match(styles, /background-color:\s*rgb\(255 255 255 \/ var\(--naviga-glass-alpha\)\)/);
  assert.match(styles, /backdrop-filter:\s*blur\(var\(--naviga-glass-blur\)\) saturate\(1\.08\)/);
  assert.match(styles, /\.naviga-panel\s*\{[\s\S]*?background:\s*#ffffff[\s\S]*?box-shadow:\s*inset 0 1px 0 rgba\(255,255,255,\.9\)/);
  assert.match(shell, /'--sidebar-width': '19rem'/);
  assert.match(shell, /<Sidebar variant="floating"/);
  assert.ok(shell.indexOf("router.push('/unit-management')") < shell.indexOf("router.push('/history')"));
  assert.match(shell, /min-w-0/);
  assert.match(shell, /truncate/);
  assert.match(shell, /const header = headerRef\.current;/);
  assert.match(shell, /document\.scrollingElement \?\? document\.documentElement/);
  assert.match(shell, /header\?\.style\.setProperty\('--naviga-glass-alpha'/);
  assert.match(shell, /requestAnimationFrame/);
  assert.match(shell, /NAV<span className="text-\[#0aa99c\]">IGA<\/span>/);
  assert.match(shell, /gap-2 text-\[#003f46\] transition-transform/);
});
